### ISSUE TITLE
Update translations 

### ISSUE THREAD

**Issue by bertrandfalguiere** [ipfs-shipyard/ipld-explorer-components#242]
This module is used in webUI, which is used is IPFS Desktop. Significant additions have been made in several languages (German, Italian, French at least, possibly Chinese), and they missed the IPFS Desktop 11 realease.
This shows that updating translations of this component is not in the release process of IPFS Desktop (I'll open an issue for that). 
I would be great if they could be ready for when go-ipfs 0.6 triggers a new IPFS Desktop release.

**Comment by bertrandfalguiere** [comment]
Issue already exists: https://github.com/ipfs-shipyard/ipfs-webui/issues/1370

**Comment by jessicaschilling** [comment]
Ref https://github.com/ipfs-shipyard/ipfs-webui/issues/1477#issuecomment-620838432 -- @lidel and/or @rafaelramalho19, is there bandwidth to include this work in the next release?

**Comment by lidel** [comment]
Ugh, I was under impression that if we ship latest translations with webui:
https://github.com/ipfs-shipyard/ipfs-webui/blob/master/public/locales/fr/explore.json
we won't need to do a new release of this module, but @bertrandfalguiere  is right, **translations are not picked up**(!)

### How to reproduce

I can confirm that the latest webui it does not load French translation of IPLD Explorer  screen. To reproduce: try setting Settings → Language → French at https://webui.ipfs.io

Note that it loads https://webui.ipfs.io/locales/fr/explore.json which includes translations, but does not display them, so its a bug.

### Initial ideas

I won't have bandwidth to look into this deeper, but here are some thoughts:

- Perhaps a breaking change in i18next libs? AFAIK the latest webui and the last release of this module use different versions in `package.json`.
- We are missing regression tests for this. Disabling dependency bot would help in avoiding regressions. 
- Using the same dependency versions as in webui would be the first thing to try. 
- Looking at i18next console output in dev could also help.
